services:
  - type: static
    name: onlinetest-frontend
    root: myapp
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://yourdomain-api.onrender.com"
